POST http://localhost:5000/project
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Mjk0ZmU4OWU5MDk4Y2I5NzU2OTM5MyIsImlhdCI6MTc2NDkyMDY5NSwiZXhwIjoxNzY0OTIxNTk1fQ.ALR9rI7cwar35W2j0IOh-mLrjAUHwES6zuqaTrSju2Y

{
  "title": "Dự án mới new new new",
  "description": "Mô tả dự án mới",
  "startDate": "2024-01-01",
  "endDate": "2024-12-31"
}

###

GET http://localhost:5000/project
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Mjk0ZmU4OWU5MDk4Y2I5NzU2OTM5MyIsImlhdCI6MTc2NDkyMDY5NSwiZXhwIjoxNzY0OTIxNTk1fQ.ALR9rI7cwar35W2j0IOh-mLrjAUHwES6zuqaTrSju2Y


###

PUT http://localhost:5000/project/69328a2c71dcdc3ab98bb183
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Mjk0ZmU4OWU5MDk4Y2I5NzU2OTM5MyIsImlhdCI6MTc2NDkyMDY5NSwiZXhwIjoxNzY0OTIxNTk1fQ.ALR9rI7cwar35W2j0IOh-mLrjAUHwES6zuqaTrSju2Y

{
  "title": "Dự án mới mới" ,
  "description": "Mô tả dự án mới",
  "status": "In Progress",
  "startDate": "2024-01-01",
  "endDate": "2024-12-31"
}
###
DELETE http://localhost:5000/project/693287c7045f9bc6857d056f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Mjk0ZmU4OWU5MDk4Y2I5NzU2OTM5MyIsImlhdCI6MTc2NDkyMDY5NSwiZXhwIjoxNzY0OTIxNTk1fQ.ALR9rI7cwar35W2j0IOh-mLrjAUHwES6zuqaTrSju2Y